/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Lisa
 */
public class UnTurno extends javax.swing.JFrame {

    /**
     * Creates new form UnTurno
     */
    public UnTurno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelUnTurno = new javax.swing.JPanel();
        jLabelNroTurno = new javax.swing.JLabel();
        jLabelPaciente = new javax.swing.JLabel();
        jLabelEspecialidad = new javax.swing.JLabel();
        jLabelMedico = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jButtonAtender = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Un Turno");
        setName("unTurno"); // NOI18N

        jPanelUnTurno.setBorder(javax.swing.BorderFactory.createTitledBorder("Turno"));

        jLabelNroTurno.setText("Nro.: ");

        jLabelPaciente.setText("Paciente");

        jLabelEspecialidad.setText("Especialidad:");

        jLabelMedico.setText("Médico:");

        jLabelFecha.setText("Fecha:");

        jButtonAtender.setText("Atender");
        jButtonAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtenderActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUnTurnoLayout = new javax.swing.GroupLayout(jPanelUnTurno);
        jPanelUnTurno.setLayout(jPanelUnTurnoLayout);
        jPanelUnTurnoLayout.setHorizontalGroup(
            jPanelUnTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUnTurnoLayout.createSequentialGroup()
                .addGroup(jPanelUnTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUnTurnoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelUnTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUnTurnoLayout.createSequentialGroup()
                                .addGroup(jPanelUnTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNroTurno)
                                    .addComponent(jLabelEspecialidad))
                                .addGap(192, 192, 192)
                                .addGroup(jPanelUnTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMedico)
                                    .addComponent(jLabelPaciente)))
                            .addComponent(jLabelFecha)))
                    .addGroup(jPanelUnTurnoLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButtonAtender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanelUnTurnoLayout.setVerticalGroup(
            jPanelUnTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUnTurnoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelUnTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPaciente)
                    .addComponent(jLabelNroTurno))
                .addGap(27, 27, 27)
                .addGroup(jPanelUnTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEspecialidad)
                    .addComponent(jLabelMedico))
                .addGap(30, 30, 30)
                .addComponent(jLabelFecha)
                .addGap(26, 26, 26)
                .addGroup(jPanelUnTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAtender)
                    .addComponent(jButtonCancelar))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelUnTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelUnTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAtenderActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnTurno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtender;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabelEspecialidad;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelMedico;
    private javax.swing.JLabel jLabelNroTurno;
    private javax.swing.JLabel jLabelPaciente;
    private javax.swing.JPanel jPanelUnTurno;
    // End of variables declaration//GEN-END:variables
}
